#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $PM_REPO == "pmpermit" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1Jbm5leGlhL1BtU2VjdXJpdHkvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $PM_REPO == "PMPERMIT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1Jbm5leGlhL1BtU2VjdXJpdHkvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $PM_REPO =~ $regex ]]
    then
        if [[ $PM_REPO_BRANCH ]]
        then
            echo "${PM_REPO}/archive/${PM_REPO_BRANCH}.zip"
        else
            echo "${PM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1Jbm5leGlhL1BtU2VjdXJpdHkvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="pmpermit.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    PMPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $PMPATH
    echo "    Starting Userbot    "
    echo "
            Starting Pm Permit Bot
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
